// "use client ";
import "./globals.css";
import Navbar from "@/app/compnent/navbar/Navbar";
// import  ProviderContext  from "@/app/context/Context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        {/* <ProviderContext> */}
          <Navbar />
          {children}
        {/* </ProviderContext> */}
      </body>
    </html>
  );
}
